### PR TITLE
Add warning about deprecation

### PR DESCRIPTION
**Pull request by athei**
Parity will no longer maintain this. We will be pushing for making `wasmparser` and `wasmencoder` `no_std` compatible.

### CODE REVIEW

**Comment by hunjixin** [comment]
@athei  could you show me the code about wasmparser/wasmencoder for reference

**Comment by hunjixin** [comment]
https://github.com/bytecodealliance/wasm-tools/tree/main/crates/wasm-mutate/src

**Comment by athei** [comment]
If you only want to parse (but not write) and need `no_std` you should use this: https://crates.io/crates/wasmparser-nost

**Comment by hunjixin** [comment]
> If you only want to parse (but not write) and need `no_std` you should use this: https://crates.io/crates/wasmparser-nost

edit wasm is not  easy to use

**Review by pepyakin — APPROVED** [review]

**Review by HCastano — APPROVED** [review]
🪦

**Pull request merged**
