### PR TITLE
Fix linting issues related to the simd macro

### PR DESCRIPTION
**Pull request by chevdor**
The `simd!` macro is mainly (133 times) used with 2 expressions. Sometimes (18 times) however, a 3rd is needed.

This PR does not fix all the clippy issues, the rest is addressed in #306 and #305.

Initially, `simd!` was defined as:
```
#[cfg(feature="simd")]
macro_rules! simd {
	($writer: expr, $byte: expr, $other:expr) => ({
		$writer.write(&[SIMD_PREFIX])?;
		VarUint32::from($byte).serialize($writer)?;
		$other;
	})
}
```

Linting the expansion of the macro results in grumbles in **many cases** similar to the one we can see below.

```
warning: statement with no effect
    --> src/elements/ops.rs:1711:3
     |
1711 |         $other;
     |         ^^^^^^^
...
2296 |             I32x4TruncUF32x4Sat => simd!(writer, I32X4_TRUNC_U_F32X4_SAT, ()),
     |                                    ------------------------------------------ in this macro invocation
     |
     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#no_effect
     = note: this warning originates in the macro `simd` (in Nightly builds, run with -Z macro-backtrace for more info)
```

We have 2 options:
- disable the linting warnings
- have an additionnal macro

This PR proposes the second option.
What do you think @pepyakin ? 
If you agree with the option and have better naming ideas, please let me know.

### CODE REVIEW

**Comment by chevdor** [comment]
Alternatively, we can also keep a single macro and use `{}` instead of `()`

**Comment by athei** [comment]
I am really in favor of just disabling the lint for the macro. The only bad thing that that this does is making the **generated** code less readable. Now we are changing the **generating** code to be less readable (more macros) in order to fix a non-issue.

**Comment by chevdor** [comment]
@athei I am also not a big fan of the change as I did it in the PR and after thinking further I think the best option is to keep one single macro but pass `{}` and not `()` for the macro calls where we don`t need the 3rd expression.

That makes the linter happy, allows not sutting down any linting and actually makes sense this way IMO.

**Comment by athei** [comment]
> I think the best option is to keep one single macro but pass `{}` and not `()` for the macro calls where we don`t need the 3rd expression.

Sounds good.

**Comment by chevdor** [comment]
ok, so let's not merge this PR yet, I will rewrite it.

**Review by athei — APPROVED** [review]

**Pull request merged**
