### PR TITLE
Fix testsuite on windows

### PR DESCRIPTION
**Pull request by devashishdxt**
Testsuite fails on windows because of manual filepath handling. Fixed it by using `std::path::Path` instead of `str`.

### CODE REVIEW

**Comment by devashishdxt** [comment]
The clippy issue is not related to this PR. I'm not sure if I should fix it in this PR?

**Review by pepyakin — APPROVED** [review]

**Comment by devashishdxt** [comment]
@pepyakin Can this be merged?

**Comment by pepyakin** [comment]
technically we need two thumbs up, @athei r?

**Comment by athei** [comment]
> The clippy issue is not related to this PR. I'm not sure if I should fix it in this PR?

Yes please fix the clippy issue. Then I merge Thanks.

**Pull request closed without merging**
