### PR TITLE
move to rust 2021

### PR DESCRIPTION
**Pull request by NukeManDan**

### CODE REVIEW

**Review by KiChjang — APPROVED** [review]

**Review by athei — APPROVED** [review]

**Comment by pepyakin** [comment]
I know this is not something we keep an eye on, but what's the MSRV of that change?

**Comment by NukeManDan** [comment]
Dumb question: MSRV is The "minimum supported Rust version" right?

"increments are a breaking Semver change" policy may applies to this repository 🤔 should it?

> The relevant check should update to the minimal dependency versions first, in order to make sure newer compatible versions are ignored in this regard.

AFAIK minimal stable toolchain version with rust edition 2021 is rustc 1.56.0 
https://blog.rust-lang.org/2021/10/21/Rust-1.56.0.html

This could be propagated in all change logs and maybe include a version bump. But what type? patch, minor or major?

**Comment by athei** [comment]
Changing the edition isn't a breaking change because different edition crates can depend on each other. However, this also bumps the required Rust version.

I think we should apply these two changes to this PR:

- Bump to `0.45`
- Add `rust-version = "1.56"

**Comment by NukeManDan** [comment]
> THE version you want to target is 1.56.1 and the last .1 is important.

from Will, this is what srtool is using and is tested.

**Comment by athei** [comment]
Not sure how this is important because that is only a security fix and nothing that interacts with compatibility.

**Comment by NukeManDan** [comment]
`rust-version = "1.56.1"` introduced

For reference, I tried to get this to `cargo build` with 1.56.0 and it failed with
```
error: package `...` cannot be built because it requires rustc 1.56.1 or newer, while the currently active rustc version is 1.56.0
```
With `--ignore-rust-version` it _does_ build with 1.56.0, as expected.

**Comment by athei** [comment]
> For reference, I tried to get this to cargo build with 1.56.0 and it failed with

My post stated "1.56" and **not** "1.56.0". The fix version is just noise here.

**Comment by NukeManDan** [comment]
Based on a quick DM, it was decided this PR should be merged :handshake:

**Pull request merged**
