### PR TITLE
WIP: Implement name section parsing

### PR DESCRIPTION
**Pull request by emk**
Spec: https://github.com/WebAssembly/design/blob/master/BinaryEncoding.md#name-section
Issue: https://github.com/paritytech/parity-wasm/issues/129

This is a basic implementation of *.wasm name sections, including serialization and deserialization. As per the discussion with @NikVolf on #129, we implement a custom `IndexMap` type.

Before merging this, we should consider the following issues:

- [x] SECURITY: The custom `IndexMap` structure is exposed to a denial of service attack. This can be easily prevented; see below for discussion.
- [x] ~~We currently require all entries in an `IndexMap` to be in ascending order, as required by the standard. We could relax this check if we needed to handle non-compliant files.~~ I'm going to leave this check in unless somebody objects.
- [ ] We need a real-world *.wasm file with a module and local name sections.
- [ ] We probably want top-level `mod.module_name_section()`, `mod.function_name_section()` and `mod.local_name_section()` APIs to make it easy to access the relevant sections. Only one of each section is allowed, so this would make semantic sense.
- [ ] It looks like name sections will normally be left unparsed. But we should probably go ahead and hook them up to the fuzzer manually.

**Security and `IndexMap`:**

It's possible to create a local name section containing three entries, for the indices `u32::MAX-2`, `u32::MAX-1` and `u32::MAX`, each of which contains an entry for a local variable with index `u32::MAX`. This will consume an utterly ridiculous amount of RAM.

There are three possible fixes, all of which are relatively easy:

1. Switch from `IndexMap<T>` to `BTreeMap<u32, T>`.
2. Keep the index `IndexMap<T>` API, but reimplement it using a private `BTreeMap<u32, T>`. This allows us to replace the implementation later without breaking the API.
3. Keep `IndexMap<T>`, but refuse to deserialize maps containing too many gaps. This would require a slightly different `Deserialize` API, particular to deal with `IndexMap<IndexMap<String>>`.

It would also be possible to have some combination of the above, with a feature flag to switch between them.

### CODE REVIEW

**Comment by NikVolf** [comment]
Cool! Yeah, about this security issue - indeed, there should be some limit of what indices the map can contain (it is naturally limited by number of entries in other sections, and we should enforce this)

Maybe we can the whole thing lazy?

So when the module serializes, it loads name section as `Unparsed`, but then when we add deserialization of this section as a method on module instance?

something like that:

```rust
impl Module {
    fn parse_names(mut self) -> Self { ... }
}
```

So invoking code can do smth like that:

```
let module_with_names: Module = deserialize_buffer(&[..]).parse_names();
```

This way `parse_names`  can work a bit more smart and peek existing sections to see what limit on the indices should be?

**Comment by emk** [comment]
> This way `parse_names` can work a bit more smart and peek existing sections to see what limit on the indices should be?

This is an excellent idea, but it means that `IndexMap<IndexMap<String>>` is going to need to check both the number of functions, and also the number of variables in each function, which means that `IndexMap` can't implement any kind of generic `Deserialize` method.

I'll try to find a solution that minimizes boilerplate. :-)

**Comment by emk** [comment]
@NikVolf OK, I've updated the deserialization routines to take a `&Module` as an argument, and to fail with an error if any of the names are out of bounds. It's a little bit complicated, but it should address the security issue nicely.

We still need a few things, included in the checklist above: (1) a test file with a module name and local variable names, (2) the `parse_names` API you suggested, and (3) fuzzer intergration. But most of the heavy coding is done.

I may not get a change to finish this before Friday, so please feel free to steal it from me and finish it if you need it sooner. Thank you for all your help!

**Comment by NikVolf** [comment]
Great job so far, no rush on this

**Comment by emk** [comment]
I'm hoping to get some more time for this tomorrow. We'll see. :-)

**Pull request merged**
