### PR TITLE
Implement trunc_sat ops

### PR DESCRIPTION
**Pull request by osa1**

### CODE REVIEW

**Comment by athei** [comment]
Shouldn't we merge the missing instructions? @NikVolf @pepyakin

**Comment by NikVolf** [comment]
I don't believe those are from V1 spec are they?

**Comment by osa1** [comment]
I don't know which revision added these, but they're standard now. You can see them at the bottom of instruction index: https://webassembly.github.io/spec/core/appendix/index-instructions.html#index-instr

**Comment by NikVolf** [comment]
I think they should be implemented in similar way to atomics:
https://github.com/paritytech/parity-wasm/blob/bb191e850da6ccfbb6b098dddd5a882a59afc212/src/elements/ops.rs#L308

(dedicated entry in enum and under feature-flag)

**Comment by osa1** [comment]
Why? Atomics are not standard, but these are.

**Comment by athei** [comment]
I think because while being part of the standard they are not part of the MVP. I found no easy way to look that up. That said, I am OK with adding instructions that are part of the standard without a feature flag no matter when they where added.

Users of parity-wasm that can't handle these new instructions must make sure to reject then. As a matter of fact this is exactly what pallet-contracts does.

**Comment by NikVolf** [comment]
> Why? Atomics are not standard, but these are.

`parity-wasm` cannot afford to produce no error on something that produced error in previous versions

Those ops were later addition

**Comment by athei** [comment]
Are there any major drawbacks to your use case when guarding the new instructions behind a new feature flag? It will certainly make our life easier.

**Comment by athei** [comment]
Closing for lack of activity. @osa1 open a new PR if you want to see this merged (behind a feature flag).

**Pull request closed without merging**
